server:
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webzio
    username: postgres
    password: root
    hikari:
      pool-name: WebzIoHikariPool
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  jta:
    enabled: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.webzio.springboot: INFO


jwt:
  secretKey: supersecretjwtkey
  expirationMinute: 10

swagger:
  contact-name: Harallamb Dimitresku
  contact-mail: hdimitresku@gmail.com
  app-name: Webz.io
  app-version: 1.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
